name: NOAA alerts
skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        - name: zone_id
          type: text
          label: Zone-ID - check https://alerts.weather.gov/#us
          value: ""
          placeholder: ILZ026

