name: NOAA alerts
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: label
          type: label
          value: "Please check https://alerts.weather.gov/#us for your Zone-ID"
        - name: zone_id
          type: text
          label: Zone-ID
          value: ""
          placeholder: ILZ026
        - name: urgency
          type: select
          label: Urgency
          options: "Immediate|Immediate;Expected|Immediate,Expected;Future|Immediate,Expected,Future"
          value: "Immediate"
        - name: severity
          type: select
          label: Severity
          options: "Extreme|Extreme;Severe|Extreme,Severe;Moderate|Extreme,Severe,Moderate;Minor|Extreme,Severe,Moderate,Minor"
          value: "Extreme"
        - name: certainty
          type: select
          label: Certainty
          options: "Observed|Observed;Likely|Observed,Likely;Possible|Observed,Likely,Possible"
          value: "Observed"
